language: node_js
services:
  - mongodb
  - docker
script:
  - npm test
  - ./bin/release-docker-image -b ${RELEASE_BRANCH} -r ${TRAVIS_BRANCH} -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
