{% extends '../layouts/application.swig' %}
{% block container %}
  <h1 class='page-header'>{{currentPage.name}}</h1>
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-12">
          <h3>Children portrait session</h3>
          <p>
            Session fee is £30 for one child, £15 for each additional child
          </p>
          <p>
          Portrait session takes about 20-30 minutes and results in 10-15 images. I am offering portrait sessions for children from 6 months till 15 years+. The session can take place in an outdoor location or at your home. Parent(s) are present during portrait sessions and may need to help (to communicate with the child), especially if the child is shy or does not like the camera.
          </p>
        </div>
        <div class="col-md-12">
          <h3>Family session</h3>
          <p>
            Session fee is £75
          </p>
          <p>
          The session lasts up to 2 hours, can be organized at two different locations (for instance your home and park or beach). The session can and should include breaks, naps and snacks. The resulting gallery is between 40-60 images (which would make a great photobook). Part of the session is dedicated to children and family portraits.
          </p>
        </div>
        <div class="col-md-12">
          <h3>Newborn/young baby lifestyle session</h3>
          <p>
            Session fee is £100
          </p>
          <p>
          This type of session is for newborns and babies up to 8 months old (before they start to walk).
          The session lasts between 2-4 hours with breaks for feeding, napping, comforting. The special focus of this session is to capture precious moments of interaction and details with your little one - pouts, yawns, tiny fingers and toes, milestones in case of older babies - first smiles, rolling over, sitting. The session takes place at your home, part of it can be done outside if you wish to make a walk with your little one. The resulting gallery is 40-60 images.
          </p>
        </div>
        <div class="col-md-12">
          <h3>Baby’s first year package</h3>
          <p>
            Session fee is £200
          </p>
          <p>
          It includes three photo shoots during the first year of your baby’s life. The sessions are organized to capture important milestones as sitting, crawling, first steps. A range of portraits will be made of the baby and the whole family during each session. Each session will result in 40-60 images, sessions will last 2-4 hours with younger baby, and 2-3 hours with 6 months and older baby.
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div>
        <p>
          <h3>What happens after the session</h3>
        </p>
        <p>
          I carefully select and edit your images and prepare your online gallery for you to see. About two weeks after your session you will receive the access information to your online gallery. It can be shared with your family and friends if you wish, and it will be available to you for three weeks to decide which prints and other products you would like to order.
        </p>
      </div>
      <div>
        <div class="panel panel-default">
          <div class="panel-heading">Products</div>
          <ul class="list-group">
            <li class="list-group-item">Unmounted prints - from £10</li>
            <li class="list-group-item">Mounted prints - from £50</li>
            <li class="list-group-item">Photobooks - from £150</li>
            <li class="list-group-item">Digital images and collections - from £25</li>
          </ul>
        </div>
      </div>
      <div class='well'>
        All session fees include pre-shoot consultation, my time on location and the time it takes to edit your images; online gallery to view your images. Please note that the session fee does not include any products. Session fee should be paid at the time of booking to secure your place.
      </div>
    </div>
  </div>
{% endblock %}
