{% extends '../layouts/application.swig' %}
{% block container %}
  <h1 class='page-header'>{{currentPage.name}}</h1>
  <p>Queste feste avete un'opportunità unica per conservare per sempre gli splendidi ricordi che l'atmosfera natalizia regalerà alla vostra famiglia. Un'ottima idea per conservare con voi l'immagine dei vostri bambini prima che crescano troppo rapidamente, da condividere con i nonni e con membri della famiglia vicini e lontani.</p>
  <p>L'offerta comprende un servizio all'aperto (parco, spiaggia, centro...) per fotografie spontanee durante momenti di gioco, di svago e che mostrano la forza e la bellezza dei legami fra di voi, con i vostri bambini e tra fratelli e sorelle.</p>
  <p>Il servizio si deve svolgere tra il 18 ed il 29 Dicembre 2016, durerà circa un'ora ed avrete circa 30 fotografie tra cui scegliere.</p>
  <p>Il servizio è a partire da €65 ed include 5 stampe 13x18 cm. Altre stampe o altri formati possono essere acquistati a partire da €7.</p>
{%endblock%}
